services:
  user-service:
    build:
      context: ./
      dockerfile: services/user-service/Dockerfile
    ports:
      - "50055:50051"
    env_file:
      - ./services/user-service/.env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - mongo
      - redis
    networks:
      - app-network

  auth-service:
    build:
      context: ./
      dockerfile: services/auth-service/Dockerfile
    ports:
      - "50052:50052"
    env_file:
      - ./services/auth-service/.env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - mongo
      - redis
      - user-service
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27027:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user-service
      - auth-service
    networks:
      - app-network

volumes:
  mongo-data:
  redis-data:

networks:
  app-network:
    driver: bridge